name: CD – Dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch: {}

concurrency:
  group: cd-dev
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/reusable/deploy.yml
    with:
      environment: dev
      namespace: w08-dev
      image_tag: ${{ github.sha }}
    secrets: inherit
